#CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=Train --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=300 --eval --compare-hist --label=label --hist-atts=age --hist-num-samples=300000 --test-frac=0.3 --num-eval-try=5 --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=Retrain --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=300 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=Stale --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=0 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=Finetune --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=10 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=NegGrad+ --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=5 --alpha=0.95 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
#CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=NegGrad --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=1 --alpha=0 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1

CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=Retrain --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=300 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=Stale --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=0 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=Finetune --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=10 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=NegGrad+ --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=5 --alpha=0.95 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
#CUDA_VISIBLE_DEVICES=1 python train_tvae.py --mode=NegGrad --dataset=census --datafile=data/census_train.csv --metadatafile=data/census.json --epochs=1 --alpha=0 --eval --eval-deleted --compare-hist --label=label --hist-atts=age --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/census_Train.pkl --filters=data/census_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=census-v1
