CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=Train --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=300 --eval --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=300000 --test-frac=0.3 --num-eval-try=5 --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=Retrain --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=300 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=Stale --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=0 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=Finetune --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=20 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=NegGrad+ --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=5 --alpha=0.9999999 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
#CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=NegGrad --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=1 --alpha=0 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=100000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters1.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1

CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=Retrain --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=300 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=Stale --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=0 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=Finetune --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=10 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=NegGrad+ --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=2 --alpha=0.9999999 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
#CUDA_VISIBLE_DEVICES=2 python train_tvae.py --mode=NegGrad --dataset=forest --datafile=data/covtype_train.csv --metadatafile=data/covtype.json --epochs=1 --alpha=0 --eval --eval-deleted --compare-hist --label=label --hist-atts=Elevation --hist-num-samples=200000 --test-frac=0.3 --num-eval-try=5 --pre-model=models/forest_Train.pkl --filters=data/forest_filters2.json --wandb-mode=online --wandb-project=tvae-unlearning-largerbench --wandb-entity=USERNAME --wandb-group-name=forest-v1
